apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "recipe-job.fullname" . }}
  labels:
    {{- include "recipe-job.labels" . | nindent 4 }}
spec:
  completions: {{ .Values.gpusCount }}  # 1 gpu for master + (n-1 for workers)
  parallelism: {{ .Values.gpusCount }}  # Run all pods at the same time
  completionMode: Indexed  # Ensures each pod is tracked separately (pod index == worker Rank)
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "recipe-job.selectorLabels" . | nindent 8 }}
    spec:
      subdomain: {{ include "recipe-job.fullname" . }}
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "recipe-job.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command: ["bash", "-c", "echo $JOB_COMPLETION_INDEX"]
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}